# Site information
site_name: 'Site name'
site_description: 'Site description'
site_author: 'Site author'
site_url: 'https://my.site.com'

# Copyright
copyright: 'Copyright &copy;'

# Configuration
docs_dir: docs
theme:
  name: material
  language: 'en'
  palette:
    primary: 'orange'
    accent: 'orange'
  logo:
    icon: 'cloud'
  feature:
    tabs: true

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - codehilite:
      guess_lang: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
